<?xml version="1.0" encoding="UTF-8"?>
2017-09-30 13:42:25,780 - log.py[line:88] - INFO:   run 正确登录.
2017-09-30 13:42:25,780 - remote_connection.py[line:478] - DEBUG: POST http://127.0.0.1:4723/wd/hub/session/ac869d90-9ed4-42a6-b00b-15cfcda8218b/context {"sessionId": "ac869d90-9ed4-42a6-b00b-15cfcda8218b", "name": "WEBVIEW"}
2017-09-30 13:42:25,865 - remote_connection.py[line:565] - DEBUG: Finished Request
2017-09-30 13:42:25,867 - creat_case.py[line:116] - ERROR: Message: No such context found.

2017-09-30 13:42:25,868 - remote_connection.py[line:478] - DEBUG: GET http://127.0.0.1:4723/wd/hub/session/ac869d90-9ed4-42a6-b00b-15cfcda8218b/screenshot {"sessionId": "ac869d90-9ed4-42a6-b00b-15cfcda8218b"}
